#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use yii\console\Application;

require __DIR__ . '/../vendor/autoload.php';

require __DIR__ . '/../config/env.php';
$dotenv = Dotenv::createImmutable(__DIR__ . '/../');
$dotenv->load();

defined('YII_DEBUG') || define('YII_DEBUG', true);
defined('YII_ENV') || define('YII_ENV', 'dev');
date_default_timezone_set('Europe/Moscow');

require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/../config/console.php';

exit((new Application($config))->run());
